# Generated by Django 2.2.1 on 2019-07-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0002_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppOne.Signature'),
        ),
    ]
